/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    java
    id("org.springframework.boot") version "3.4.4"
    id("io.freefair.lombok") version "8.13.1"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(platform(org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES))
    implementation(platform("com.google.cloud:spring-cloud-gcp-dependencies:6.1.1"))

    implementation("com.google.cloud:spring-cloud-gcp-starter")
    implementation("com.google.cloud:spring-cloud-gcp-starter-secretmanager")

}